---
- name: Create base path
  file:
    path: "{{ generic_dtrack_base_path }}"
    state: directory
    recurse: true
    owner: "{{ generic_dtrack_uid }}"
    group: "{{ generic_dtrack_gid }}"

- name: Create additional paths
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ generic_dtrack_uid }}"
    group: "{{ generic_dtrack_gid }}"
  loop: "{{ generic_dtrack_additional_path }}"

- name: Create frontend config from template
  template:
    src: config.json.j2
    dest: "{{ generic_dtrack_base_path }}/frontend/config.json"
    owner: "{{ generic_dtrack_uid }}"
    group: "{{ generic_dtrack_gid }}"

- name: Deploy apiserver container
  docker_container:
    name: "{{ generic_dtrack_apiserver_container_name }}"
    image: "{{ generic_dtrack_apiserver_container_image }}"
    user: "{{ generic_dtrack_uid }}:{{ generic_dtrack_gid }}"
    published_ports: "{{ generic_dtrack_apiserver_container_ports }}"
    env: "{{ generic_dtrack_apiserver_container_env | combine(generic_dtrack_apiserver_container_additional_env) }}"
    volumes: "{{ generic_dtrack_apiserver_container_volumes }}"
    links: "{{ generic_dtrack_apiserver_container_links }}"
    state: "{{ generic_dtrack_apiserver_container_state }}"
    recreate: "{{ generic_dtrack_apiserver_container_recreate }}"
    auto_remove: "{{ generic_dtrack_apiserver_container_auto_remove }}"
    cpu_quota: "{{ generic_dtrack_apiserver_container_cpu_quota }}"
    memory_reservation: "{{ generic_dtrack_apiserver_container_memory_reservation }}"
    memory_swap: "{{ generic_dtrack_apiserver_container_memory_swap }}"
    network_mode: "{{ generic_dtrack_apiserver_container_network_mode }}"
    networks: "{{ generic_dtrack_apiserver_container_networks }}"
    restart: "{{ generic_dtrack_apiserver_container_restart }}"
    restart_policy: "{{ generic_dtrack_apiserver_container_restart_policy }}"

- name: Deploy frontend container
  docker_container:
    name: "{{ generic_dtrack_frontend_container_name }}"
    image: "{{ generic_dtrack_frontend_container_image }}"
    #user: "{{ generic_dtrack_uid }}:{{ generic_dtrack_gid }}"
    published_ports: "{{ generic_dtrack_frontend_container_ports }}"
    env: "{{ generic_dtrack_frontend_container_env }}"
    volumes: "{{ generic_dtrack_frontend_container_volumes }}"
    links: "{{ generic_dtrack_frontend_container_links }}"
    state: "{{ generic_dtrack_frontend_container_state }}"
    recreate: "{{ generic_dtrack_frontend_container_recreate }}"
    auto_remove: "{{ generic_dtrack_frontend_container_auto_remove }}"
    cpu_quota: "{{ generic_dtrack_frontend_container_cpu_quota }}"
    memory_reservation: "{{ generic_dtrack_frontend_container_memory_reservation }}"
    memory_swap: "{{ generic_dtrack_frontend_container_memory_swap }}"
    network_mode: "{{ generic_dtrack_frontend_container_network_mode }}"
    networks: "{{ generic_dtrack_frontend_container_networks }}"
    restart: "{{ generic_dtrack_frontend_container_restart }}"
    restart_policy: "{{ generic_dtrack_frontend_container_restart_policy }}"

- name: Include OS specific tasks
  include_tasks:
    file: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"